export type PhoneCountry = {
  iso2: string;
  name: string;
  dialCode: string;
  flagImageUrl: string;
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso2: 'US', name: 'United States', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/us.png' },
  { iso2: 'AF', name: 'Afghanistan', dialCode: '+93', flagImageUrl: 'https://flagcdn.com/w40/af.png' },
  { iso2: 'AX', name: 'Aland Islands', dialCode: '+358', flagImageUrl: 'https://flagcdn.com/w40/ax.png' },
  { iso2: 'AL', name: 'Albania', dialCode: '+355', flagImageUrl: 'https://flagcdn.com/w40/al.png' },
  { iso2: 'DZ', name: 'Algeria', dialCode: '+213', flagImageUrl: 'https://flagcdn.com/w40/dz.png' },
  { iso2: 'AS', name: 'American Samoa', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/as.png' },
  { iso2: 'AD', name: 'Andorra', dialCode: '+376', flagImageUrl: 'https://flagcdn.com/w40/ad.png' },
  { iso2: 'AO', name: 'Angola', dialCode: '+244', flagImageUrl: 'https://flagcdn.com/w40/ao.png' },
  { iso2: 'AI', name: 'Anguilla', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/ai.png' },
  { iso2: 'AQ', name: 'Antarctica', dialCode: '+672', flagImageUrl: 'https://flagcdn.com/w40/aq.png' },
  { iso2: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/ag.png' },
  { iso2: 'AR', name: 'Argentina', dialCode: '+54', flagImageUrl: 'https://flagcdn.com/w40/ar.png' },
  { iso2: 'AM', name: 'Armenia', dialCode: '+374', flagImageUrl: 'https://flagcdn.com/w40/am.png' },
  { iso2: 'AW', name: 'Aruba', dialCode: '+297', flagImageUrl: 'https://flagcdn.com/w40/aw.png' },
  { iso2: 'AU', name: 'Australia', dialCode: '+61', flagImageUrl: 'https://flagcdn.com/w40/au.png' },
  { iso2: 'AT', name: 'Austria', dialCode: '+43', flagImageUrl: 'https://flagcdn.com/w40/at.png' },
  { iso2: 'AZ', name: 'Azerbaijan', dialCode: '+994', flagImageUrl: 'https://flagcdn.com/w40/az.png' },
  { iso2: 'BH', name: 'Bahrain', dialCode: '+973', flagImageUrl: 'https://flagcdn.com/w40/bh.png' },
  { iso2: 'BD', name: 'Bangladesh', dialCode: '+880', flagImageUrl: 'https://flagcdn.com/w40/bd.png' },
  { iso2: 'BB', name: 'Barbados', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/bb.png' },
  { iso2: 'BY', name: 'Belarus', dialCode: '+375', flagImageUrl: 'https://flagcdn.com/w40/by.png' },
  { iso2: 'BE', name: 'Belgium', dialCode: '+32', flagImageUrl: 'https://flagcdn.com/w40/be.png' },
  { iso2: 'BZ', name: 'Belize', dialCode: '+501', flagImageUrl: 'https://flagcdn.com/w40/bz.png' },
  { iso2: 'BJ', name: 'Benin', dialCode: '+229', flagImageUrl: 'https://flagcdn.com/w40/bj.png' },
  { iso2: 'BM', name: 'Bermuda', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/bm.png' },
  { iso2: 'BT', name: 'Bhutan', dialCode: '+975', flagImageUrl: 'https://flagcdn.com/w40/bt.png' },
  { iso2: 'BO', name: 'Bolivia', dialCode: '+591', flagImageUrl: 'https://flagcdn.com/w40/bo.png' },
  { iso2: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '+599', flagImageUrl: 'https://flagcdn.com/w40/bq.png' },
  { iso2: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flagImageUrl: 'https://flagcdn.com/w40/ba.png' },
  { iso2: 'BW', name: 'Botswana', dialCode: '+267', flagImageUrl: 'https://flagcdn.com/w40/bw.png' },
  { iso2: 'BV', name: 'Bouvet Island', dialCode: '+55', flagImageUrl: 'https://flagcdn.com/w40/bv.png' },
  { iso2: 'BR', name: 'Brazil', dialCode: '+55', flagImageUrl: 'https://flagcdn.com/w40/br.png' },
  { iso2: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246', flagImageUrl: 'https://flagcdn.com/w40/io.png' },
  { iso2: 'BN', name: 'Brunei', dialCode: '+673', flagImageUrl: 'https://flagcdn.com/w40/bn.png' },
  { iso2: 'BG', name: 'Bulgaria', dialCode: '+359', flagImageUrl: 'https://flagcdn.com/w40/bg.png' },
  { iso2: 'BF', name: 'Burkina Faso', dialCode: '+226', flagImageUrl: 'https://flagcdn.com/w40/bf.png' },
  { iso2: 'BI', name: 'Burundi', dialCode: '+257', flagImageUrl: 'https://flagcdn.com/w40/bi.png' },
  { iso2: 'KH', name: 'Cambodia', dialCode: '+855', flagImageUrl: 'https://flagcdn.com/w40/kh.png' },
  { iso2: 'CM', name: 'Cameroon', dialCode: '+237', flagImageUrl: 'https://flagcdn.com/w40/cm.png' },
  { iso2: 'CA', name: 'Canada', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/ca.png' },
  { iso2: 'CV', name: 'Cape Verde', dialCode: '+238', flagImageUrl: 'https://flagcdn.com/w40/cv.png' },
  { iso2: 'KY', name: 'Cayman Islands', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/ky.png' },
  { iso2: 'CF', name: 'Central African Republic', dialCode: '+236', flagImageUrl: 'https://flagcdn.com/w40/cf.png' },
  { iso2: 'TD', name: 'Chad', dialCode: '+235', flagImageUrl: 'https://flagcdn.com/w40/td.png' },
  { iso2: 'CL', name: 'Chile', dialCode: '+56', flagImageUrl: 'https://flagcdn.com/w40/cl.png' },
  { iso2: 'CN', name: 'China', dialCode: '+86', flagImageUrl: 'https://flagcdn.com/w40/cn.png' },
  { iso2: 'CX', name: 'Christmas Island', dialCode: '+61', flagImageUrl: 'https://flagcdn.com/w40/cx.png' },
  { iso2: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '+61', flagImageUrl: 'https://flagcdn.com/w40/cc.png' },
  { iso2: 'CO', name: 'Colombia', dialCode: '+57', flagImageUrl: 'https://flagcdn.com/w40/co.png' },
  { iso2: 'KM', name: 'Comoros', dialCode: '+269', flagImageUrl: 'https://flagcdn.com/w40/km.png' },
  { iso2: 'CG', name: 'Congo', dialCode: '+242', flagImageUrl: 'https://flagcdn.com/w40/cg.png' },
  { iso2: 'CK', name: 'Cook Islands', dialCode: '+682', flagImageUrl: 'https://flagcdn.com/w40/ck.png' },
  { iso2: 'CR', name: 'Costa Rica', dialCode: '+506', flagImageUrl: 'https://flagcdn.com/w40/cr.png' },
  { iso2: 'HR', name: 'Croatia', dialCode: '+385', flagImageUrl: 'https://flagcdn.com/w40/hr.png' },
  { iso2: 'CU', name: 'Cuba', dialCode: '+53', flagImageUrl: 'https://flagcdn.com/w40/cu.png' },
  { iso2: 'CW', name: 'Curacao', dialCode: '+599', flagImageUrl: 'https://flagcdn.com/w40/cw.png' },
  { iso2: 'CY', name: 'Cyprus', dialCode: '+357', flagImageUrl: 'https://flagcdn.com/w40/cy.png' },
  { iso2: 'CZ', name: 'Czech Republic', dialCode: '+420', flagImageUrl: 'https://flagcdn.com/w40/cz.png' },
  { iso2: 'CD', name: 'Democratic Republic of the Congo', dialCode: '+243', flagImageUrl: 'https://flagcdn.com/w40/cd.png' },
  { iso2: 'DK', name: 'Denmark', dialCode: '+45', flagImageUrl: 'https://flagcdn.com/w40/dk.png' },
  { iso2: 'DJ', name: 'Djibouti', dialCode: '+253', flagImageUrl: 'https://flagcdn.com/w40/dj.png' },
  { iso2: 'DM', name: 'Dominica', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/dm.png' },
  { iso2: 'DO', name: 'Dominican Republic', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/do.png' },
  { iso2: 'EC', name: 'Ecuador', dialCode: '+593', flagImageUrl: 'https://flagcdn.com/w40/ec.png' },
  { iso2: 'EG', name: 'Egypt', dialCode: '+20', flagImageUrl: 'https://flagcdn.com/w40/eg.png' },
  { iso2: 'SV', name: 'El Salvador', dialCode: '+503', flagImageUrl: 'https://flagcdn.com/w40/sv.png' },
  { iso2: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flagImageUrl: 'https://flagcdn.com/w40/gq.png' },
  { iso2: 'ER', name: 'Eritrea', dialCode: '+291', flagImageUrl: 'https://flagcdn.com/w40/er.png' },
  { iso2: 'EE', name: 'Estonia', dialCode: '+372', flagImageUrl: 'https://flagcdn.com/w40/ee.png' },
  { iso2: 'SZ', name: 'Eswatini', dialCode: '+268', flagImageUrl: 'https://flagcdn.com/w40/sz.png' },
  { iso2: 'ET', name: 'Ethiopia', dialCode: '+251', flagImageUrl: 'https://flagcdn.com/w40/et.png' },
  { iso2: 'FK', name: 'Falkland Islands', dialCode: '+500', flagImageUrl: 'https://flagcdn.com/w40/fk.png' },
  { iso2: 'FO', name: 'Faroe Islands', dialCode: '+298', flagImageUrl: 'https://flagcdn.com/w40/fo.png' },
  { iso2: 'FJ', name: 'Fiji Islands', dialCode: '+679', flagImageUrl: 'https://flagcdn.com/w40/fj.png' },
  { iso2: 'FI', name: 'Finland', dialCode: '+358', flagImageUrl: 'https://flagcdn.com/w40/fi.png' },
  { iso2: 'FR', name: 'France', dialCode: '+33', flagImageUrl: 'https://flagcdn.com/w40/fr.png' },
  { iso2: 'GF', name: 'French Guiana', dialCode: '+594', flagImageUrl: 'https://flagcdn.com/w40/gf.png' },
  { iso2: 'PF', name: 'French Polynesia', dialCode: '+689', flagImageUrl: 'https://flagcdn.com/w40/pf.png' },
  { iso2: 'TF', name: 'French Southern Territories', dialCode: '+262', flagImageUrl: 'https://flagcdn.com/w40/tf.png' },
  { iso2: 'GA', name: 'Gabon', dialCode: '+241', flagImageUrl: 'https://flagcdn.com/w40/ga.png' },
  { iso2: 'GE', name: 'Georgia', dialCode: '+995', flagImageUrl: 'https://flagcdn.com/w40/ge.png' },
  { iso2: 'DE', name: 'Germany', dialCode: '+49', flagImageUrl: 'https://flagcdn.com/w40/de.png' },
  { iso2: 'GH', name: 'Ghana', dialCode: '+233', flagImageUrl: 'https://flagcdn.com/w40/gh.png' },
  { iso2: 'GI', name: 'Gibraltar', dialCode: '+350', flagImageUrl: 'https://flagcdn.com/w40/gi.png' },
  { iso2: 'GR', name: 'Greece', dialCode: '+30', flagImageUrl: 'https://flagcdn.com/w40/gr.png' },
  { iso2: 'GL', name: 'Greenland', dialCode: '+299', flagImageUrl: 'https://flagcdn.com/w40/gl.png' },
  { iso2: 'GD', name: 'Grenada', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/gd.png' },
  { iso2: 'GP', name: 'Guadeloupe', dialCode: '+590', flagImageUrl: 'https://flagcdn.com/w40/gp.png' },
  { iso2: 'GU', name: 'Guam', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/gu.png' },
  { iso2: 'GT', name: 'Guatemala', dialCode: '+502', flagImageUrl: 'https://flagcdn.com/w40/gt.png' },
  { iso2: 'GG', name: 'Guernsey', dialCode: '+44', flagImageUrl: 'https://flagcdn.com/w40/gg.png' },
  { iso2: 'GN', name: 'Guinea', dialCode: '+224', flagImageUrl: 'https://flagcdn.com/w40/gn.png' },
  { iso2: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flagImageUrl: 'https://flagcdn.com/w40/gw.png' },
  { iso2: 'GY', name: 'Guyana', dialCode: '+592', flagImageUrl: 'https://flagcdn.com/w40/gy.png' },
  { iso2: 'HT', name: 'Haiti', dialCode: '+509', flagImageUrl: 'https://flagcdn.com/w40/ht.png' },
  { iso2: 'HM', name: 'Heard Island and McDonald Islands', dialCode: '+672', flagImageUrl: 'https://flagcdn.com/w40/hm.png' },
  { iso2: 'HN', name: 'Honduras', dialCode: '+504', flagImageUrl: 'https://flagcdn.com/w40/hn.png' },
  { iso2: 'HK', name: 'Hong Kong S.A.R.', dialCode: '+852', flagImageUrl: 'https://flagcdn.com/w40/hk.png' },
  { iso2: 'HU', name: 'Hungary', dialCode: '+36', flagImageUrl: 'https://flagcdn.com/w40/hu.png' },
  { iso2: 'IS', name: 'Iceland', dialCode: '+354', flagImageUrl: 'https://flagcdn.com/w40/is.png' },
  { iso2: 'IN', name: 'India', dialCode: '+91', flagImageUrl: 'https://flagcdn.com/w40/in.png' },
  { iso2: 'ID', name: 'Indonesia', dialCode: '+62', flagImageUrl: 'https://flagcdn.com/w40/id.png' },
  { iso2: 'IR', name: 'Iran', dialCode: '+98', flagImageUrl: 'https://flagcdn.com/w40/ir.png' },
  { iso2: 'IQ', name: 'Iraq', dialCode: '+964', flagImageUrl: 'https://flagcdn.com/w40/iq.png' },
  { iso2: 'IE', name: 'Ireland', dialCode: '+353', flagImageUrl: 'https://flagcdn.com/w40/ie.png' },
  { iso2: 'IL', name: 'Israel', dialCode: '+972', flagImageUrl: 'https://flagcdn.com/w40/il.png' },
  { iso2: 'IT', name: 'Italy', dialCode: '+39', flagImageUrl: 'https://flagcdn.com/w40/it.png' },
  { iso2: 'CI', name: 'Ivory Coast', dialCode: '+225', flagImageUrl: 'https://flagcdn.com/w40/ci.png' },
  { iso2: 'JM', name: 'Jamaica', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/jm.png' },
  { iso2: 'JP', name: 'Japan', dialCode: '+81', flagImageUrl: 'https://flagcdn.com/w40/jp.png' },
  { iso2: 'JE', name: 'Jersey', dialCode: '+44', flagImageUrl: 'https://flagcdn.com/w40/je.png' },
  { iso2: 'JO', name: 'Jordan', dialCode: '+962', flagImageUrl: 'https://flagcdn.com/w40/jo.png' },
  { iso2: 'KZ', name: 'Kazakhstan', dialCode: '+7', flagImageUrl: 'https://flagcdn.com/w40/kz.png' },
  { iso2: 'KE', name: 'Kenya', dialCode: '+254', flagImageUrl: 'https://flagcdn.com/w40/ke.png' },
  { iso2: 'KI', name: 'Kiribati', dialCode: '+686', flagImageUrl: 'https://flagcdn.com/w40/ki.png' },
  { iso2: 'XK', name: 'Kosovo', dialCode: '+383', flagImageUrl: 'https://flagcdn.com/w40/xk.png' },
  { iso2: 'KW', name: 'Kuwait', dialCode: '+965', flagImageUrl: 'https://flagcdn.com/w40/kw.png' },
  { iso2: 'KG', name: 'Kyrgyzstan', dialCode: '+996', flagImageUrl: 'https://flagcdn.com/w40/kg.png' },
  { iso2: 'LA', name: 'Laos', dialCode: '+856', flagImageUrl: 'https://flagcdn.com/w40/la.png' },
  { iso2: 'LV', name: 'Latvia', dialCode: '+371', flagImageUrl: 'https://flagcdn.com/w40/lv.png' },
  { iso2: 'LB', name: 'Lebanon', dialCode: '+961', flagImageUrl: 'https://flagcdn.com/w40/lb.png' },
  { iso2: 'LS', name: 'Lesotho', dialCode: '+266', flagImageUrl: 'https://flagcdn.com/w40/ls.png' },
  { iso2: 'LR', name: 'Liberia', dialCode: '+231', flagImageUrl: 'https://flagcdn.com/w40/lr.png' },
  { iso2: 'LY', name: 'Libya', dialCode: '+218', flagImageUrl: 'https://flagcdn.com/w40/ly.png' },
  { iso2: 'LI', name: 'Liechtenstein', dialCode: '+423', flagImageUrl: 'https://flagcdn.com/w40/li.png' },
  { iso2: 'LT', name: 'Lithuania', dialCode: '+370', flagImageUrl: 'https://flagcdn.com/w40/lt.png' },
  { iso2: 'LU', name: 'Luxembourg', dialCode: '+352', flagImageUrl: 'https://flagcdn.com/w40/lu.png' },
  { iso2: 'MO', name: 'Macau S.A.R.', dialCode: '+853', flagImageUrl: 'https://flagcdn.com/w40/mo.png' },
  { iso2: 'MG', name: 'Madagascar', dialCode: '+261', flagImageUrl: 'https://flagcdn.com/w40/mg.png' },
  { iso2: 'MW', name: 'Malawi', dialCode: '+265', flagImageUrl: 'https://flagcdn.com/w40/mw.png' },
  { iso2: 'MY', name: 'Malaysia', dialCode: '+60', flagImageUrl: 'https://flagcdn.com/w40/my.png' },
  { iso2: 'MV', name: 'Maldives', dialCode: '+960', flagImageUrl: 'https://flagcdn.com/w40/mv.png' },
  { iso2: 'ML', name: 'Mali', dialCode: '+223', flagImageUrl: 'https://flagcdn.com/w40/ml.png' },
  { iso2: 'MT', name: 'Malta', dialCode: '+356', flagImageUrl: 'https://flagcdn.com/w40/mt.png' },
  { iso2: 'IM', name: 'Man (Isle of)', dialCode: '+44', flagImageUrl: 'https://flagcdn.com/w40/im.png' },
  { iso2: 'MH', name: 'Marshall Islands', dialCode: '+692', flagImageUrl: 'https://flagcdn.com/w40/mh.png' },
  { iso2: 'MQ', name: 'Martinique', dialCode: '+596', flagImageUrl: 'https://flagcdn.com/w40/mq.png' },
  { iso2: 'MR', name: 'Mauritania', dialCode: '+222', flagImageUrl: 'https://flagcdn.com/w40/mr.png' },
  { iso2: 'MU', name: 'Mauritius', dialCode: '+230', flagImageUrl: 'https://flagcdn.com/w40/mu.png' },
  { iso2: 'YT', name: 'Mayotte', dialCode: '+262', flagImageUrl: 'https://flagcdn.com/w40/yt.png' },
  { iso2: 'MX', name: 'Mexico', dialCode: '+52', flagImageUrl: 'https://flagcdn.com/w40/mx.png' },
  { iso2: 'FM', name: 'Micronesia', dialCode: '+691', flagImageUrl: 'https://flagcdn.com/w40/fm.png' },
  { iso2: 'MD', name: 'Moldova', dialCode: '+373', flagImageUrl: 'https://flagcdn.com/w40/md.png' },
  { iso2: 'MC', name: 'Monaco', dialCode: '+377', flagImageUrl: 'https://flagcdn.com/w40/mc.png' },
  { iso2: 'MN', name: 'Mongolia', dialCode: '+976', flagImageUrl: 'https://flagcdn.com/w40/mn.png' },
  { iso2: 'ME', name: 'Montenegro', dialCode: '+382', flagImageUrl: 'https://flagcdn.com/w40/me.png' },
  { iso2: 'MS', name: 'Montserrat', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/ms.png' },
  { iso2: 'MA', name: 'Morocco', dialCode: '+212', flagImageUrl: 'https://flagcdn.com/w40/ma.png' },
  { iso2: 'MZ', name: 'Mozambique', dialCode: '+258', flagImageUrl: 'https://flagcdn.com/w40/mz.png' },
  { iso2: 'MM', name: 'Myanmar', dialCode: '+95', flagImageUrl: 'https://flagcdn.com/w40/mm.png' },
  { iso2: 'NA', name: 'Namibia', dialCode: '+264', flagImageUrl: 'https://flagcdn.com/w40/na.png' },
  { iso2: 'NR', name: 'Nauru', dialCode: '+674', flagImageUrl: 'https://flagcdn.com/w40/nr.png' },
  { iso2: 'NP', name: 'Nepal', dialCode: '+977', flagImageUrl: 'https://flagcdn.com/w40/np.png' },
  { iso2: 'NL', name: 'Netherlands', dialCode: '+31', flagImageUrl: 'https://flagcdn.com/w40/nl.png' },
  { iso2: 'NC', name: 'New Caledonia', dialCode: '+687', flagImageUrl: 'https://flagcdn.com/w40/nc.png' },
  { iso2: 'NZ', name: 'New Zealand', dialCode: '+64', flagImageUrl: 'https://flagcdn.com/w40/nz.png' },
  { iso2: 'NI', name: 'Nicaragua', dialCode: '+505', flagImageUrl: 'https://flagcdn.com/w40/ni.png' },
  { iso2: 'NE', name: 'Niger', dialCode: '+227', flagImageUrl: 'https://flagcdn.com/w40/ne.png' },
  { iso2: 'NG', name: 'Nigeria', dialCode: '+234', flagImageUrl: 'https://flagcdn.com/w40/ng.png' },
  { iso2: 'NU', name: 'Niue', dialCode: '+683', flagImageUrl: 'https://flagcdn.com/w40/nu.png' },
  { iso2: 'NF', name: 'Norfolk Island', dialCode: '+672', flagImageUrl: 'https://flagcdn.com/w40/nf.png' },
  { iso2: 'KP', name: 'North Korea', dialCode: '+850', flagImageUrl: 'https://flagcdn.com/w40/kp.png' },
  { iso2: 'MK', name: 'North Macedonia', dialCode: '+389', flagImageUrl: 'https://flagcdn.com/w40/mk.png' },
  { iso2: 'MP', name: 'Northern Mariana Islands', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/mp.png' },
  { iso2: 'NO', name: 'Norway', dialCode: '+47', flagImageUrl: 'https://flagcdn.com/w40/no.png' },
  { iso2: 'OM', name: 'Oman', dialCode: '+968', flagImageUrl: 'https://flagcdn.com/w40/om.png' },
  { iso2: 'PK', name: 'Pakistan', dialCode: '+92', flagImageUrl: 'https://flagcdn.com/w40/pk.png' },
  { iso2: 'PW', name: 'Palau', dialCode: '+680', flagImageUrl: 'https://flagcdn.com/w40/pw.png' },
  { iso2: 'PS', name: 'Palestinian Territory Occupied', dialCode: '+970', flagImageUrl: 'https://flagcdn.com/w40/ps.png' },
  { iso2: 'PA', name: 'Panama', dialCode: '+507', flagImageUrl: 'https://flagcdn.com/w40/pa.png' },
  { iso2: 'PG', name: 'Papua New Guinea', dialCode: '+675', flagImageUrl: 'https://flagcdn.com/w40/pg.png' },
  { iso2: 'PY', name: 'Paraguay', dialCode: '+595', flagImageUrl: 'https://flagcdn.com/w40/py.png' },
  { iso2: 'PE', name: 'Peru', dialCode: '+51', flagImageUrl: 'https://flagcdn.com/w40/pe.png' },
  { iso2: 'PH', name: 'Philippines', dialCode: '+63', flagImageUrl: 'https://flagcdn.com/w40/ph.png' },
  { iso2: 'PN', name: 'Pitcairn Island', dialCode: '+870', flagImageUrl: 'https://flagcdn.com/w40/pn.png' },
  { iso2: 'PL', name: 'Poland', dialCode: '+48', flagImageUrl: 'https://flagcdn.com/w40/pl.png' },
  { iso2: 'PT', name: 'Portugal', dialCode: '+351', flagImageUrl: 'https://flagcdn.com/w40/pt.png' },
  { iso2: 'PR', name: 'Puerto Rico', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/pr.png' },
  { iso2: 'QA', name: 'Qatar', dialCode: '+974', flagImageUrl: 'https://flagcdn.com/w40/qa.png' },
  { iso2: 'RE', name: 'Reunion', dialCode: '+262', flagImageUrl: 'https://flagcdn.com/w40/re.png' },
  { iso2: 'RO', name: 'Romania', dialCode: '+40', flagImageUrl: 'https://flagcdn.com/w40/ro.png' },
  { iso2: 'RU', name: 'Russia', dialCode: '+7', flagImageUrl: 'https://flagcdn.com/w40/ru.png' },
  { iso2: 'RW', name: 'Rwanda', dialCode: '+250', flagImageUrl: 'https://flagcdn.com/w40/rw.png' },
  { iso2: 'SH', name: 'Saint Helena', dialCode: '+290', flagImageUrl: 'https://flagcdn.com/w40/sh.png' },
  { iso2: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/kn.png' },
  { iso2: 'LC', name: 'Saint Lucia', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/lc.png' },
  { iso2: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', flagImageUrl: 'https://flagcdn.com/w40/pm.png' },
  { iso2: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/vc.png' },
  { iso2: 'BL', name: 'Saint-Barthelemy', dialCode: '+590', flagImageUrl: 'https://flagcdn.com/w40/bl.png' },
  { iso2: 'MF', name: 'Saint-Martin (French part)', dialCode: '+590', flagImageUrl: 'https://flagcdn.com/w40/mf.png' },
  { iso2: 'WS', name: 'Samoa', dialCode: '+685', flagImageUrl: 'https://flagcdn.com/w40/ws.png' },
  { iso2: 'SM', name: 'San Marino', dialCode: '+378', flagImageUrl: 'https://flagcdn.com/w40/sm.png' },
  { iso2: 'ST', name: 'Sao Tome and Principe', dialCode: '+239', flagImageUrl: 'https://flagcdn.com/w40/st.png' },
  { iso2: 'SA', name: 'Saudi Arabia', dialCode: '+966', flagImageUrl: 'https://flagcdn.com/w40/sa.png' },
  { iso2: 'SN', name: 'Senegal', dialCode: '+221', flagImageUrl: 'https://flagcdn.com/w40/sn.png' },
  { iso2: 'RS', name: 'Serbia', dialCode: '+381', flagImageUrl: 'https://flagcdn.com/w40/rs.png' },
  { iso2: 'SC', name: 'Seychelles', dialCode: '+248', flagImageUrl: 'https://flagcdn.com/w40/sc.png' },
  { iso2: 'SL', name: 'Sierra Leone', dialCode: '+232', flagImageUrl: 'https://flagcdn.com/w40/sl.png' },
  { iso2: 'SG', name: 'Singapore', dialCode: '+65', flagImageUrl: 'https://flagcdn.com/w40/sg.png' },
  { iso2: 'SX', name: 'Sint Maarten (Dutch part)', dialCode: '+1721', flagImageUrl: 'https://flagcdn.com/w40/sx.png' },
  { iso2: 'SK', name: 'Slovakia', dialCode: '+421', flagImageUrl: 'https://flagcdn.com/w40/sk.png' },
  { iso2: 'SI', name: 'Slovenia', dialCode: '+386', flagImageUrl: 'https://flagcdn.com/w40/si.png' },
  { iso2: 'SB', name: 'Solomon Islands', dialCode: '+677', flagImageUrl: 'https://flagcdn.com/w40/sb.png' },
  { iso2: 'SO', name: 'Somalia', dialCode: '+252', flagImageUrl: 'https://flagcdn.com/w40/so.png' },
  { iso2: 'ZA', name: 'South Africa', dialCode: '+27', flagImageUrl: 'https://flagcdn.com/w40/za.png' },
  { iso2: 'GS', name: 'South Georgia', dialCode: '+500', flagImageUrl: 'https://flagcdn.com/w40/gs.png' },
  { iso2: 'KR', name: 'South Korea', dialCode: '+82', flagImageUrl: 'https://flagcdn.com/w40/kr.png' },
  { iso2: 'SS', name: 'South Sudan', dialCode: '+211', flagImageUrl: 'https://flagcdn.com/w40/ss.png' },
  { iso2: 'ES', name: 'Spain', dialCode: '+34', flagImageUrl: 'https://flagcdn.com/w40/es.png' },
  { iso2: 'LK', name: 'Sri Lanka', dialCode: '+94', flagImageUrl: 'https://flagcdn.com/w40/lk.png' },
  { iso2: 'SD', name: 'Sudan', dialCode: '+249', flagImageUrl: 'https://flagcdn.com/w40/sd.png' },
  { iso2: 'SR', name: 'Suriname', dialCode: '+597', flagImageUrl: 'https://flagcdn.com/w40/sr.png' },
  { iso2: 'SJ', name: 'Svalbard and Jan Mayen Islands', dialCode: '+47', flagImageUrl: 'https://flagcdn.com/w40/sj.png' },
  { iso2: 'SE', name: 'Sweden', dialCode: '+46', flagImageUrl: 'https://flagcdn.com/w40/se.png' },
  { iso2: 'CH', name: 'Switzerland', dialCode: '+41', flagImageUrl: 'https://flagcdn.com/w40/ch.png' },
  { iso2: 'SY', name: 'Syria', dialCode: '+963', flagImageUrl: 'https://flagcdn.com/w40/sy.png' },
  { iso2: 'TW', name: 'Taiwan', dialCode: '+886', flagImageUrl: 'https://flagcdn.com/w40/tw.png' },
  { iso2: 'TJ', name: 'Tajikistan', dialCode: '+992', flagImageUrl: 'https://flagcdn.com/w40/tj.png' },
  { iso2: 'TZ', name: 'Tanzania', dialCode: '+255', flagImageUrl: 'https://flagcdn.com/w40/tz.png' },
  { iso2: 'TH', name: 'Thailand', dialCode: '+66', flagImageUrl: 'https://flagcdn.com/w40/th.png' },
  { iso2: 'BS', name: 'The Bahamas', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/bs.png' },
  { iso2: 'GM', name: 'The Gambia', dialCode: '+220', flagImageUrl: 'https://flagcdn.com/w40/gm.png' },
  { iso2: 'TL', name: 'Timor-Leste', dialCode: '+670', flagImageUrl: 'https://flagcdn.com/w40/tl.png' },
  { iso2: 'TG', name: 'Togo', dialCode: '+228', flagImageUrl: 'https://flagcdn.com/w40/tg.png' },
  { iso2: 'TK', name: 'Tokelau', dialCode: '+690', flagImageUrl: 'https://flagcdn.com/w40/tk.png' },
  { iso2: 'TO', name: 'Tonga', dialCode: '+676', flagImageUrl: 'https://flagcdn.com/w40/to.png' },
  { iso2: 'TT', name: 'Trinidad and Tobago', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/tt.png' },
  { iso2: 'TN', name: 'Tunisia', dialCode: '+216', flagImageUrl: 'https://flagcdn.com/w40/tn.png' },
  { iso2: 'TR', name: 'Turkey', dialCode: '+90', flagImageUrl: 'https://flagcdn.com/w40/tr.png' },
  { iso2: 'TM', name: 'Turkmenistan', dialCode: '+993', flagImageUrl: 'https://flagcdn.com/w40/tm.png' },
  { iso2: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/tc.png' },
  { iso2: 'TV', name: 'Tuvalu', dialCode: '+688', flagImageUrl: 'https://flagcdn.com/w40/tv.png' },
  { iso2: 'UG', name: 'Uganda', dialCode: '+256', flagImageUrl: 'https://flagcdn.com/w40/ug.png' },
  { iso2: 'UA', name: 'Ukraine', dialCode: '+380', flagImageUrl: 'https://flagcdn.com/w40/ua.png' },
  { iso2: 'AE', name: 'United Arab Emirates', dialCode: '+971', flagImageUrl: 'https://flagcdn.com/w40/ae.png' },
  { iso2: 'GB', name: 'United Kingdom', dialCode: '+44', flagImageUrl: 'https://flagcdn.com/w40/gb.png' },
  { iso2: 'UM', name: 'United States Minor Outlying Islands', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/um.png' },
  { iso2: 'UY', name: 'Uruguay', dialCode: '+598', flagImageUrl: 'https://flagcdn.com/w40/uy.png' },
  { iso2: 'UZ', name: 'Uzbekistan', dialCode: '+998', flagImageUrl: 'https://flagcdn.com/w40/uz.png' },
  { iso2: 'VU', name: 'Vanuatu', dialCode: '+678', flagImageUrl: 'https://flagcdn.com/w40/vu.png' },
  { iso2: 'VA', name: 'Vatican City State (Holy See)', dialCode: '+379', flagImageUrl: 'https://flagcdn.com/w40/va.png' },
  { iso2: 'VE', name: 'Venezuela', dialCode: '+58', flagImageUrl: 'https://flagcdn.com/w40/ve.png' },
  { iso2: 'VN', name: 'Vietnam', dialCode: '+84', flagImageUrl: 'https://flagcdn.com/w40/vn.png' },
  { iso2: 'VG', name: 'Virgin Islands (British)', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/vg.png' },
  { iso2: 'VI', name: 'Virgin Islands (US)', dialCode: '+1', flagImageUrl: 'https://flagcdn.com/w40/vi.png' },
  { iso2: 'WF', name: 'Wallis and Futuna Islands', dialCode: '+681', flagImageUrl: 'https://flagcdn.com/w40/wf.png' },
  { iso2: 'EH', name: 'Western Sahara', dialCode: '+212', flagImageUrl: 'https://flagcdn.com/w40/eh.png' },
  { iso2: 'YE', name: 'Yemen', dialCode: '+967', flagImageUrl: 'https://flagcdn.com/w40/ye.png' },
  { iso2: 'ZM', name: 'Zambia', dialCode: '+260', flagImageUrl: 'https://flagcdn.com/w40/zm.png' },
  { iso2: 'ZW', name: 'Zimbabwe', dialCode: '+263', flagImageUrl: 'https://flagcdn.com/w40/zw.png' },
];

export const DEFAULT_PHONE_COUNTRY_ISO2 = "US";